spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hardcore_test
    username: root
    password: 123456
  cache:
    type: redis
    redis:
      time-to-live: 60s
      key-prefix: wbomb
  redis:
    database: 0
    port: 6379
    host: localhost

server:
  port: 8000
